#!/usr/bin/env python3
"""Run the tool-routing evaluation against the configured real model and tools."""

import argparse
import json
import os
import sys
import time
from datetime import datetime, timezone
from pathlib import Path

import openai

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT))

from agent.executor import _collect_stream, _parse_args, _tool_call_id
from agent.prompts import build_messages
from agent.tools import TOOL_SCHEMAS, dispatch_tool, result_to_json
from data.finance_data import set_api_key
from data.storage import get_active_llm_profile_id, get_llm_profiles, load_config

DEFAULT_CASES = ROOT / "evals" / "tool_routing_cases.jsonl"
DEFAULT_RESULT = ROOT / "evals" / "results" / "latest.json"
DEFAULT_REPORT = ROOT / "docs" / "EVALUATION.md"


def load_cases(path):
    with open(path, encoding="utf-8") as f:
        return [json.loads(line) for line in f if line.strip()]


def active_profile():
    profiles = get_llm_profiles()
    active_id = get_active_llm_profile_id()
    profile = next((p for p in profiles if p.get("id") == active_id), None)
    profile = profile or (profiles[0] if profiles else None)
    if not profile or not profile.get("api_key") or not profile.get("model"):
        raise RuntimeError("No configured LLM profile with an API key and model")
    set_api_key(load_config().get("api_key") or "demo")
    return profile


def successful_result(value):
    return isinstance(value, dict) and not value.get("error")


def run_case(client, profile, case, max_rounds=4):
    started = time.monotonic()
    messages = build_messages(case["lang"], [
        {"role": "user", "content": case["question"]}
    ])
    calls, answer, terminal_error = [], "", None
    for _ in range(max_rounds):
        try:
            response = client.chat.completions.create(
                model=profile["model"], messages=messages,
                tools=TOOL_SCHEMAS, tool_choice="auto", stream=True,
                temperature=0,
            )
            partial, requested = _collect_stream(response)
        except Exception as exc:
            terminal_error = f"model request failed: {type(exc).__name__}: {str(exc)[:300]}"
            break
        if not requested:
            answer += partial or ""
            break
        messages.append({
            "role": "assistant", "content": partial or None,
            "tool_calls": [
                {"id": _tool_call_id(call, i), "type": "function",
                 "function": {"name": call["name"], "arguments": call["arguments"]}}
                for i, call in enumerate(requested)
            ],
        })
        for i, call in enumerate(requested):
            args = _parse_args(call.get("arguments", ""))
            value = dispatch_tool(call.get("name", ""), args)
            ok = successful_result(value)
            calls.append({"name": call.get("name", ""), "args": args,
                          "success": ok,
                          "error": value.get("error") if isinstance(value, dict) else None})
            messages.append({"role": "tool", "tool_call_id": _tool_call_id(call, i),
                             "content": result_to_json(value)})
    else:
        terminal_error = "maximum agent rounds reached"

    expected = case["expected_tools"]
    actual = [c["name"] for c in calls]
    routing_ok = set(actual) == set(expected)
    execution_ok = bool(calls) and all(c["success"] for c in calls)
    answer_ok = bool(answer.strip()) and terminal_error is None
    return {
        **case, "actual_tools": actual, "calls": calls,
        "routing_ok": routing_ok, "execution_ok": execution_ok,
        "answer_ok": answer_ok,
        "end_to_end_ok": routing_ok and execution_ok and answer_ok,
        "answer_preview": answer.strip()[:500], "error": terminal_error,
        "latency_seconds": round(time.monotonic() - started, 2),
    }


def summarize(rows):
    tool_calls = [call for row in rows for call in row["calls"]]
    n = len(rows)
    return {
        "cases": n,
        "tool_calls": len(tool_calls),
        "tool_routing_accuracy": sum(r["routing_ok"] for r in rows) / n if n else 0,
        "tool_execution_success_rate": (
            sum(c["success"] for c in tool_calls) / len(tool_calls) if tool_calls else 0),
        "end_to_end_completion_rate": sum(r["end_to_end_ok"] for r in rows) / n if n else 0,
        "total_latency_seconds": round(sum(r["latency_seconds"] for r in rows), 2),
    }


def pct(value):
    return f"{value * 100:.1f}%"


def write_report(path, run):
    s, rows = run["summary"], run["results"]
    failures = [r for r in rows if not r["end_to_end_ok"]]
    lines = [
        "# Agent Evaluation",
        "",
        "> This file is generated by `python scripts/evaluate_agent.py` from a real run.",
        "",
        "## Latest run",
        "",
        f"- Run time (UTC): `{run['run_at']}`",
        f"- Model: `{run['model']}`",
        f"- Cases: **{s['cases']}**",
        f"- Tool calls executed: **{s['tool_calls']}**",
        f"- Tool routing accuracy: **{pct(s['tool_routing_accuracy'])}**",
        f"- Tool execution success rate: **{pct(s['tool_execution_success_rate'])}**",
        f"- End-to-end completion rate: **{pct(s['end_to_end_completion_rate'])}**",
        f"- Total measured latency: **{s['total_latency_seconds']:.2f}s**",
        "",
        "Routing is correct only when the set of called tools exactly matches `expected_tools`. "
        "Tool execution succeeds when a real tool returns no top-level error. End-to-end completion "
        "requires correct routing, successful execution, and a non-empty final model answer.",
        "",
        "## Case results",
        "",
        "| ID | Expected | Actual | Route | Execute | E2E | Latency |",
        "| --- | --- | --- | --- | --- | --- | ---: |",
    ]
    for r in rows:
        mark = lambda ok: "PASS" if ok else "FAIL"
        lines.append(f"| {r['id']} | {', '.join(r['expected_tools'])} | "
                     f"{', '.join(r['actual_tools']) or 'none'} | {mark(r['routing_ok'])} | "
                     f"{mark(r['execution_ok'])} | {mark(r['end_to_end_ok'])} | "
                     f"{r['latency_seconds']:.2f}s |")
    lines += ["", "## Failures", ""]
    if failures:
        for r in failures:
            reasons = []
            if not r["routing_ok"]:
                reasons.append("tool set did not exactly match the annotation")
            if not r["execution_ok"]:
                reasons.append("one or more tool calls failed")
            if not r["answer_ok"]:
                reasons.append(r["error"] or "no valid final answer")
            lines.append(f"- `{r['id']}` — expected `{r['expected_tools']}`, got "
                         f"`{r['actual_tools']}`. {'; '.join(reasons)}.")
    else:
        lines.append("No failed cases in this run.")
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text("\n".join(lines) + "\n", encoding="utf-8")


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--cases", type=Path, default=DEFAULT_CASES)
    parser.add_argument("--result", type=Path, default=DEFAULT_RESULT)
    parser.add_argument("--report", type=Path, default=DEFAULT_REPORT)
    parser.add_argument("--limit", type=int)
    args = parser.parse_args()
    cases = load_cases(args.cases)
    if args.limit:
        cases = cases[:args.limit]
    profile = active_profile()
    client = openai.OpenAI(api_key=profile["api_key"],
                           base_url=profile.get("base_url") or None, timeout=90)
    rows = []
    for index, case in enumerate(cases, 1):
        row = run_case(client, profile, case)
        rows.append(row)
        print(f"[{index:02d}/{len(cases)}] {case['id']}: "
              f"route={'PASS' if row['routing_ok'] else 'FAIL'} "
              f"exec={'PASS' if row['execution_ok'] else 'FAIL'} "
              f"e2e={'PASS' if row['end_to_end_ok'] else 'FAIL'}", flush=True)
    run = {"run_at": datetime.now(timezone.utc).isoformat(),
           "model": profile["model"], "summary": summarize(rows), "results": rows}
    args.result.parent.mkdir(parents=True, exist_ok=True)
    args.result.write_text(json.dumps(run, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
    write_report(args.report, run)
    print(json.dumps(run["summary"], indent=2))


if __name__ == "__main__":
    main()
